### ISSUE TITLE
Update docs on merge to main

### ISSUE THREAD

**Issue by nelson-barnett** [The-Lammert-Lab/tinnitus-reconstruction#220]
Just manually updated the docs and realized that we can automate the whole process. Shouldn't be complicated, but just requires figuring out how to do it. Manually, all that needs to be done is run `mkdocs gh-deploy` from a python venv with the proper dependencies. I had that set up from a while ago so I'm not sure exactly what dependencies it needs off the top of my head. We'll just need to figure out how to make CI do it properly.

**Comment by alec-hoyland** [comment]
So there's two ways that we can do it... One is that we can set it up as a git pre-commit hook so that it'll run before we try to push code. That way the updated docs will always be part of any push to GitHub that we do.

The other way is to make a GitHub action that rebuilds the docs whenever we merge code.

On May 22, 2023 9:30:03 PM EDT, Nelson Barnett ***@***.***> wrote:
>Just manually updated the docs and realized that we can automate the whole process. Shouldn't be complicated, but just requires figuring out how to do it. Manually, all that needs to be done is run `mkdocs gh-deploy` from a python venv with the proper dependencies. I had that set up from a while ago so I'm not sure exactly what dependencies it needs off the top of my head. We'll just need to figure out how to make CI do it properly.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/The-Lammert-Lab/tinnitus-reconstruction/issues/220
>You are receiving this because you were assigned.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nelson-barnett** [comment]
I have a git hook for building the docs, but not for deploying them. That would be nbd to add. 

However, I think it's probably better to have both the building and deploying as a GH action. That way nobody needs to do anything for the it all to stay up to date. I can try to set that up when I have a chance, but it might not be for a bit.
