### ISSUE TITLE
when to convert spectrum to db

### ISSUE THREAD

**Issue by nelson-barnett** [The-Lammert-Lab/tinnitus-reconstruction#269]
In our meeting on Monday, we experimented with wav2spect returning `s = mean(10*log10(abs(s)), 2);` instead of `s = mean(abs(s),2);`. Currently, we do the `10*log10()` operation after, when needed (which is almost always). To do the first version, it would break a ton of stuff. Is the first version actually better? Should we implement this?

**Comment by alec-hoyland** [comment]
Yes, I think we want to take the mean of the spectrum in decibels, so `mean(amplitude_to_db(s, 2)` is correct.

Note that we should probably be taking the power spectrum here in dB, so instead of `abs` we should be using `.*2`.

```matlab
y = function amplitude_to_db(x)
    y = 10. * log10(x .* 2)
end
```

**Comment by nelson-barnett** [comment]
Gotcha. Do you know what the resulting perceptual effect would be from this? Also, why is it better? I clearly see the difference, I just don't know the theoretical justification for doing it one way over another.

**Comment by alec-hoyland** [comment]
S is a short-time Fourier transform of the waveform. Since the signal is not [statistically stationary](https://en.wikipedia.org/wiki/Stationary_process), we take overlapping chunks of the waveform, window them, and then perform the FFT (via the [`spectrogram`](https://www.mathworks.com/help/signal/ref/spectrogram.html) function. 

The result from this process is a spectrogram of size $k \times r$ where $k$ is the number of "spect-time" samples, which is proportional to the length of the signal, the number of overlaps, and the length of the window. Thus, each column is an FFT of a segment of the original signal. Each row is of length $r$ and is the number of FFT points (`nfft/2+1`).

This is in amplitude values, so we take the square to get the power spectrum and then convert from the power spectrum in linear scale to decibel scale. 

For our purposes, we don't want $k$ different log-power spectrograms, because we only want one signal, so we average them together. It's better to average in the log-power spectrogram-space rather than in amplitude space, though sometimes you can get the same answer either way. It's a question of "log then sum" or "sum then log." Here's a [StackOverflow](https://math.stackexchange.com/questions/3821181/sum-of-log-versus-log-of-sum) answer about it. The log of sums is always equal or smaller than the sum of logs due to the AM-GM inequality.

**Comment by nelson-barnett** [comment]
> Yes, I think we want to take the mean of the spectrum in decibels, so `mean(amplitude_to_db(s, 2)` is correct.
> 
> Note that we should probably be taking the power spectrum here in dB, so instead of `abs` we should be using `.*2`.
> 
> ```matlab
> function y = amplitude_to_db(x)
>     y = 10. * log10(x .* 2)
> end
> ```

We get complex values from `spectrogram`, which is why we're taking the absolute value. That still seems necessary to me in this case.

**Comment by nelson-barnett** [comment]
> S is a short-time Fourier transform of the waveform. Since the signal is not [statistically stationary](https://en.wikipedia.org/wiki/Stationary_process), we take overlapping chunks of the waveform, window them, and then perform the FFT (via the [`spectrogram`](https://www.mathworks.com/help/signal/ref/spectrogram.html) function.
> 
> The result from this process is a spectrogram of size k×r where k is the number of "spect-time" samples, which is proportional to the length of the signal, the number of overlaps, and the length of the window. Thus, each column is an FFT of a segment of the original signal. Each row is of length r and is the number of FFT points (`nfft/2+1`).
> 
> This is in amplitude values, so we take the square to get the power spectrum and then convert from the power spectrum in linear scale to decibel scale.
> 
> For our purposes, we don't want k different log-power spectrograms, because we only want one signal, so we average them together. It's better to average in the log-power spectrogram-space rather than in amplitude space basically only because it makes more sense logically (we want an average of things in decibels), though sometimes you can get the same answer either way, so mathematically it's less important than all the other steps. The best justification I can give is that you can think of decibels as a nonlinear unit (as opposed to "linear" units like kilograms vs. grams), so it's better to get the units right before doing any other calculations. It's a question of "log then sum" or "sum then log." Here's a [StackOverflow](https://math.stackexchange.com/questions/3821181/sum-of-log-versus-log-of-sum) answer about it. The log of sums is always equal or smaller than the sum of logs due to the AM-GM inequality.

Thank you for the explanation. That makes sense. I was hesitant to make such a big change after all the experiments we've done with it being as it is now, but since it really won't make that big of a difference and is a more logical sequence, I'm much more convinced.

**Comment by alec-hoyland** [comment]
> > Yes, I think we want to take the mean of the spectrum in decibels, so `mean(amplitude_to_db(s, 2)` is correct.
> > Note that we should probably be taking the power spectrum here in dB, so instead of `abs` we should be using `.*2`.
> > ```matlab
> > function y = amplitude_to_db(x)
> >     y = 10. * log10(x .* 2)
> > end
> > ```
> 
> We get complex values from `spectrogram`, which is why we're taking the absolute value. That still seems necessary to me in this case.

I was being lax with my syntax. What we want is $|S|^2 = S \odot \bar{S}$, which is to say, S elementwise-times the complex conjugate of S, which in MATLAB would be `abs(s)^2` or `s .* conj(s)`, which get you the same result (https://www.mathworks.com/help/matlab/ref/abs.html?searchHighlight=abs&s_tid=srchtitle_support_results_1_abs#budexws-5).

Maybe we _don't_ want the power spectrum? I'm not sure. For most analysis you want the power spectrum but since we're using these signals for playback, maybe we don't?

**Comment by nelson-barnett** [comment]
Here is a comparison of the two methods. Also, I searched the repo, and `wav2spect` is never used for playback purposes. It's only used in analysis scripts and `bootstrap_reconstruction_synth.m`.

![todB_first_or_second](https://github.com/The-Lammert-Lab/tinnitus-reconstruction/assets/93552032/4d193cb5-81f4-4991-b8ab-5a976c574132)

**Comment by alec-hoyland** [comment]
Nice! That's a great visualization and it shows exactly what we should expect to see which is that taking the log after summing is smaller and magnitude than taking the sum after taking the log.

**Comment by nelson-barnett** [comment]
Yep! I'll make the change to the blue plot everywhere I can find.
